datatypes xsd = "http://www.w3.org/2001/XMLSchema-datatypes"

default namespace = "http://www.sgmlguru.org/ns/vml"

namespace sg = "http://www.sgmlguru.org/ns/vml"
namespace a = "http://relaxng.org/ns/compatibility/annotations/1.0"
namespace xlink = "http://www.w3.org/1999/xlink"

id.att = attribute id { xsd:ID }

status.att = attribute status { text }

lang.att = attribute xml:lang { text }

string.att = attribute string { text }

# Simple Xlink attributes
xlink.basic.att =
  [ a:defaultValue = "simple" ] attribute xlink:type { "simple" }?,
  attribute xlink:href { text }?,
  attribute xlink:title { text }?
xlink.subdoc.att =
  xlink.basic.att,
  attribute xlink:role { text }?
xlink.picture.att =
  xlink.subdoc.att,
  [ a:defaultValue = "embed" ] attribute xlink:show { "embed" }?,
  [ a:defaultValue = "onLoad" ] attribute xlink:actuate { "onLoad" }?
xlink.simple.att =
  xlink.subdoc.att,
  attribute xlink:show {
    "new" | "replace" | "embed" | "other" | "none"
  }?,
  attribute xlink:actuate { "onLoad" | "onRequest" | "other" | "none" }?

# Link element
link = element link { xlink.simple.att, empty }

# TBA projects structure
vml = element vml { vml.attlist, base?, resources* }
vml.attlist = id.att?

# TBA link to resource (URN)
resources = element resources { resources.attlist, metadata?, base?, resource* }
resources.attlist = id.att?

resource = element resource { resource.attlist, metadata?, base, version* }
resource.attlist = id.att?

base = element base { base.attlist, text }
base.attlist = id.att?

version = element version { version.attlist, metadata*, rev, file*, version* }
version.attlist &= status.att?, id.att?, string.att?

file = element file { file.attlist, metadata?, url? }
file.attlist = id.att?

rev = element rev { rev.attlist, text }
rev.attlist = id.att?

url = element url { url.attlist, text }
url.attlist &= lang.att?, id.att?


# Metadata - TBA, for now text only
metadata = element metadata { metadata.attlist, link*, foreign? }
metadata.attlist &= id.att?

foreign = element foreign { foreign-nodes }

foreign-elements = element * - (sg:*) { anything }*
foreign-attributes = attribute * {text}*
foreign-nodes = ( foreign-elements | foreign-attributes )*

anything = ( element * - (sg:*) { anything } | attribute * {text} | text )*

foreign.attlist = attribute * { text }



start = vml